### ISSUE TITLE
Unexplained Error thrown when attempting to upload a file to the Workbench with an existing filename

### ISSUE THREAD

**Issue by StanConv** [SkynetRTN/afterglow-access#26]
Unexplained Error thrown when attempting to upload a file to the Workbench with an existing filename

steps to recreate:

- upload a file into Workbench
- try to upload the same file a second time into the same directory
- a "Failed" notification appears.
- click on the information icon
- "Unexpected error" is displayed

This should be handled by opening a dialog which asks if you want to Replace [the existing file]/Rename [the Workbench filename for being uploaded]/Cancel [the operation]

**Comment by jhaislip** [comment]
Thanks Stan!  I've made the error message more clear, but am not able to implement the replacing/renaming feature at this time.
