### ISSUE TITLE
Display data lost when composite image is saved to Workbench

### ISSUE THREAD

**Issue by StanConv** [SkynetRTN/afterglow-access#27]
All display settings are lost when a Composite image is saved to the Workbench. This can be very disheartening if you have spent time working on Background level percentile and saturation level percentiles to create your composite image! While it is true that you can save the Composite as a .jpg, this does not allow work to be resumed per layer. Should we offer the ability to save display data for Composite images? Perhaps download all, including all settings as a composite of a new type which can be read by Afterglow when reloaded (of course this would not make sense to any other program)

**Comment by vkoupr** [comment]
Planning to save the visualization info in FITS headers once we standardize the keywords.
