### ISSUE TITLE
Add Downsample and Percentile Clipping to source extraction settings

### ISSUE THREAD

**Issue by vkoupr** [SkynetRTN/afterglow-access#38]
Downsampling image before source extraction greatly helps it for normally sampled or oversampled images. The current default in the Core is 2, but there are situations when higher or lower values give a better result.

The corresponding SourceExtractionSettings schema field is "downsample". Label: "Downsample" or "Downsampling Factor". Type: integer. Minimum: 1. Maximum: no limit. Default: 2.

**Comment by vkoupr** [comment]
Two more settings to help the detection in noisy images: `SourceExtractionSettings.clip_lo` and `clip_hi`. Both are floats 0 to 100 inclusive (clip_lo < clip_hi), clip_lo = 0 and clip_hi = 100 disable clipping on the corresponding side.

Label: "Pre-extraction Percentile Clipping", "Low" and "High". Defaults: clip_lo = 0, clip_hi = 100 for the regular source extraction/photometry; clip_lo = 10, clip_hi = 99 for the WCS calibration.

**Comment by jhaislip** [comment]
For now,  I'm going to check if clip_lo==0 && clip_hi==100 and dynamically change them to 10 and 90 respectively when the settings are used for WCS.  If we decide that we need a completely independent set of configuration values for WCS then the UI will need to be modified to accommodate.
